AWSTemplateFormatVersion: 2010-09-09
Description: Lacework AWS Config Security Audit Integration (Member Accounts)
Parameters:
  ResourceNamePrefix:
    Default: customerdemo
    Description: >-
      Names of resources created by the stack will be prefixed with this value
      to ensure uniqueness.
    Type: String
    MinLength: '1'
    MaxLength: '45'
    AllowedPattern: '^[a-zA-Z0-9]+(?:-[a-zA-Z0-9]+)*$'
    ConstraintDescription: >-
      Invalid resource name prefix.  Must match pattern
      ^[a-zA-Z0-9]+(?:-[a-zA-Z0-9]+)*$
  LaceworkAccountName:
    Default: customerdemo
    Description: >-
      Names of resources created by the stack will be prefixed with this value
      to ensure uniqueness.
    Type: String
    MinLength: '1'
    MaxLength: '45'
    AllowedPattern: '^[a-zA-Z0-9]+(?:-[a-zA-Z0-9]+)*$'
    ConstraintDescription: >-
      Invalid resource name prefix.  Must match pattern
      ^[a-zA-Z0-9]+(?:-[a-zA-Z0-9]+)*$
  ExternalSuffix:
    Default: ExternalSuffix
    Type: String
Resources:
  LaceworkCWSSACrossAccountAccessRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: !Join
        - '-'
        - - !Ref ResourceNamePrefix
          - laceworkcwsrole-sa
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action: 'sts:AssumeRole'
            Effect: Allow
            Principal:
              AWS: 'arn:aws:iam::434813966438:role/lacework-platform'
            Condition:
              StringEquals:
                'sts:ExternalId': !Join [':',[!Sub "lweid:aws:v2:${LaceworkAccountName}:${AWS::AccountId}", !Ref ExternalSuffix]]
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/SecurityAudit'
  LaceworkCWSPolicy:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyName: LaceworkCWSPolicy
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: GetAccountAlias
            Action:
              - 'iam:ListAccountAliases'
            Effect: Allow
            Resource: '*'
          - Sid: Debug
            Action:
              - 'cloudtrail:DescribeTrails'
              - 'cloudtrail:GetTrailStatus'
              - 'eks:ListTagsForResource'
              - 's3:GetBucketPolicy'
              - 's3:GetBucketLocation'
              - 'sns:GetTopicAttributes'
              - 'sns:ListSubscriptions'
              - 'sns:ListTopics'
            Effect: Allow
            Resource: '*'
          - Sid: EfsPolicies
            Action:
              - 'elasticfilesystem:DescribeFileSystemPolicy'
              - 'elasticfilesystem:DescribeLifecycleConfiguration'
              - 'elasticfilesystem:DescribeAccessPoints'
              - 'elasticfilesystem:DescribeAccountPreferences'
              - 'elasticfilesystem:DescribeBackupPolicy'
              - 'elasticfilesystem:DescribeReplicationConfigurations'
              - 'elasticfilesystem:ListTagsForResource'
            Effect: Allow
            Resource: '*'
          - Sid: SagemakerPolicies
            Action:
              - 'sagemaker:GetLineageGroupPolicy'
              - 'sagemaker:GetModelPackageGroupPolicy'
            Effect: Allow
            Resource: '*'
          - Sid: IdentityStoreReadOnly
            Action:
              - 'identitystore:DescribeGroup'
              - 'identitystore:DescribeGroupMembership'
              - 'identitystore:DescribeUser'
              - 'identitystore:ListGroupMemberships'
              - 'identitystore:ListGroupMembershipsForMember'
              - 'identitystore:ListGroups'
              - 'identitystore:ListUsers'
            Effect: Allow
            Resource: '*'
          - Sid: SSOReadOnly
            Action:
              - 'sso:DescribeAccountAssignmentDeletionStatus'
              - 'sso:DescribeInstanceAccessControlAttributeConfiguration'
              - 'sso:GetInlinePolicyForPermissionSet'
            Effect: Allow
            Resource: '*'
          - Sid: APIGATEWAY
            Action:
              - 'apigateway:GET'
            Effect: Allow
            Resource: '*'
          - Sid: APIGATEWAYV2
            Action:
              - 'apigatewayv2:GET'
            Effect: Allow
            Resource: '*'
          - Sid: SNS
            Action:
              - 'sns:GetDataProtectionPolicy'
              - 'sns:ListPlatformApplications'
              - 'sns:GetSubscriptionAttributes'
            Effect: Allow
            Resource: '*'
          - Sid: GLUE
            Action:
              - 'glue:ListWorkflows'
              - 'glue:BatchGetWorkflows'
              - 'glue:GetTags'
              - 'glue:GetTables'
              - 'glue:GetTable'
            Effect: Allow
            Resource: '*'
          - Sid: GLACIER
            Action:
              - 'glacier:ListTagsForVault'
            Effect: Allow
            Resource: '*'
          - Sid: CODEBUILD
            Action:
              - 'codebuild:ListBuilds'
              - 'codebuild:BatchGetBuilds'
            Effect: Allow
            Resource: '*'
          - Sid: WAFREGIONAL
            Action:
              - 'waf-regional:ListRules'
              - 'waf-regional:GetRule'
              - 'waf-regional:ListRuleGroups'
              - 'waf-regional:GetRuleGroup'
              - 'waf-regional:ListActivatedRulesInRuleGroup'
            Effect: Allow
            Resource: '*'
          - Sid: NETWORKFIREWALL
            Effect: Allow
            Action:
              - 'network-firewall:DescribeLoggingConfiguration'
            Resource: '*'
          - Sid: WAFV2
            Effect: Allow
            Action:
              - 'wafv2:ListWebACLs'
              - 'wafv2:ListRegexPatternSets'
              - 'wafv2:ListIPSets'
            Resource:
              - '*'
          - Sid: STATES
            Action:
              - 'states:ListTagsForResource'
            Effect: Allow
            Resource: '*'
      Roles:
        - !Ref LaceworkCWSSACrossAccountAccessRole