AWSTemplateFormatVersion: 2010-09-09
Description: Lacework AWS CloudTrail and Config Security Audit Integration (Log Account)
Parameters:
  ResourceNamePrefix:
    Description: >-
      Names of resources created by the stack will be prefixed with this value
      to ensure uniqueness.
    Type: String
    Default: laceworkalliances
    MinLength: '1'
    MaxLength: '45'
    AllowedPattern: '^[a-zA-Z0-9]+(?:-[a-zA-Z0-9]+)*$'
    ConstraintDescription: >-
      Invalid resource name prefix value.  Must match pattern
      ^[a-zA-Z0-9]+(?:-[a-zA-Z0-9]+)*$
  ExternalID:
    Default: 4CEBE3B
    Description: >-
      The cross-account access role created by the stack will use this value for
      its ExternalID.
    Type: String
    MinLength: '2'
    MaxLength: '1224'
  ExistingTrailBucketName:
    Description: >-
      Provide the name of the S3 bucket for your existing trail setup.  The
      bucket must be owned by the current account.
    Default: ''
    Type: String
    MaxLength: '128'
  KMSKeyIdentifierArn:
    Description: Provide the ARN of the KMS key for decrypting S3 log files if necessary.
    Default: ''
    Type: String
  SqsQueueUrl:
    Type: String
    Description: The SQS Queue URL.
    AllowedPattern: '^(([^:/?#]+):)?(//([^/?#]*))?([^?#]*)(\?([^#]*))?(#(.*))?'
    ConstraintDescription: Contains a URL/URI pattern only, ie. https://sqs.<region>.amazonaws.com/<account>/<name>
    Default: "https://sqs.<region>.amazonaws.com/<account>/<name>"
  SqsQueueArn:
    Type: String
    Description: The SQS Queue Arn.
Conditions:
  UseKMSDecrypt: !Not [!Equals [!Ref KMSKeyIdentifierArn, '']]
Resources:
  LaceworkCWSSACrossAccountAccessRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: !Join
        - ''
        - - !Ref ResourceNamePrefix
          - '-laceworkcwssarole'
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action: 'sts:AssumeRole'
            Effect: Allow
            Principal:
              AWS: 'arn:aws:iam::434813966438:role/lacework-platform'
            Condition:
              StringEquals:
                'sts:ExternalId': !Ref ExternalID
  LaceworkCWSPolicy:
    Type: 'AWS::IAM::ManagedPolicy'
    Properties:
      ManagedPolicyName: !Sub "LaceworkCWSLogPolicy-${AWS::AccountId}"
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: ConsumeNotifications
            Action:
              - 'sqs:GetQueueAttributes'
              - 'sqs:GetQueueUrl'
              - 'sqs:DeleteMessage'
              - 'sqs:ReceiveMessage'
            Effect: Allow
            Resource: !Ref SqsQueueArn
          - Sid: ListLogFiles
            Action:
              - 's3:ListBucket'
            Effect: Allow
            Resource: !Join ['',["arn:aws:s3:::", !Ref ExistingTrailBucketName, "/*AWSLogs/*" ]]
            Condition:
              StringLike:
                's3:prefix':
                  - '*AWSLogs/'
          - Sid: ReadLogFiles
            Action:
              - 's3:Get*'
            Effect: Allow
            Resource: !Join ['',["arn:aws:s3:::", !Ref ExistingTrailBucketName, "/*AWSLogs/*" ]]
          - Sid: GetAccountAlias
            Action:
              - 'iam:ListAccountAliases'
            Effect: Allow
            Resource: '*'
          - Sid: Debug
            Action:
              - 'cloudtrail:DescribeTrails'
              - 'cloudtrail:GetTrailStatus'
              - 'eks:ListTagsForResource'
              - 's3:GetBucketPolicy'
              - 's3:GetBucketLocation'
              - 'sns:GetTopicAttributes'
              - 'sns:ListSubscriptions'
              - 'sns:ListTopics'
            Effect: Allow
            Resource: '*'
      Roles:
        - !Ref LaceworkCWSSACrossAccountAccessRole
  LaceworkCWSDecryptPolicy:
    Type: 'AWS::IAM::Policy'
    Condition: UseKMSDecrypt
    Properties:
      PolicyName: LaceworkCWSDecryptPolicy
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: DecryptLogFiles
            Action:
              - 'kms:Decrypt'
            Effect: Allow
            Resource: !Ref KMSKeyIdentifierArn
      Roles:
        - !Ref LaceworkCWSSACrossAccountAccessRole
Outputs:
  RoleARN:
    Description: >-
      Cross-account access role ARN to share with Lacework for CloudTrail
      integration
    Value: !GetAtt
      - LaceworkCWSSACrossAccountAccessRole
      - Arn
  SQSQueueURL:
    Description: SQS queue URL to share with Lacework for CloudTrail Integration
    Value: !Ref SqsQueueUrl
  TemplateVersion:
    Description: Template version
    Value: '1.1'

